// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWxQro5-i0DchdTRI82N3qHOyksiGAjQs',
    appId: '1:133022683923:android:37039849a5b46cba31c0e6',
    messagingSenderId: '133022683923',
    projectId: 'mychat-eee79',
    storageBucket: 'mychat-eee79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXZ-MA2CvqMBbIWlAJSH75XluAIxaAOTE',
    appId: '1:133022683923:ios:4c38cdce9465cbd231c0e6',
    messagingSenderId: '133022683923',
    projectId: 'mychat-eee79',
    storageBucket: 'mychat-eee79.firebasestorage.app',
    androidClientId: '133022683923-v78gc7j25dutlta1ijk8j4tpf84gu9du.apps.googleusercontent.com',
    iosClientId: '133022683923-gtf3scr35rombr4t3mg9r8g8gl0tc3ea.apps.googleusercontent.com',
    iosBundleId: 'com.example.mychat',
  );

}