name: mychat
description: "A new Flutter project."
#
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
#    for firebase
  firebase_core: ^4.2.0
#  for firebase auth
  firebase_auth: ^6.1.1
#  for google sign-in
#  using old version bcz i was unable to resolve error GoogleSignInException(code GoogleSignInExceptionCode.clientConfigurationError, serverClientId must be provided on Android, null)
  google_sign_in: ^5.4.2
#  cloud firestore database
  cloud_firestore: ^6.0.3
# for user profile picture
  path_provider: ^2.1.5
  cached_network_image: ^3.4.1
#  to pick images from phone
  image_picker: ^1.2.0
#  for accessing firebase storage
  firebase_storage: ^13.0.3
# for showing emojis in chat
  emoji_picker_flutter: ^4.3.0
#  for push notifications
  firebase_messaging: ^16.0.3

#  for storing images o gallery
  gallery_saver_plus: ^3.2.9

#  for location sharing
  google_maps_flutter: ^2.13.1
  location: ^8.0.1
  flutter_polyline_points: ^3.1.0


  cupertino_icons: ^1.0.8

#  to store profile picture
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.8.0
#  google_sign_in_android: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_launcher_icons: "^0.14.4"
#
#flutter_launcher_icons:
#  android: "icon_launcher"
#  ios: true
#  image_path: "images/chat.png"
#  min_sdk_android: 21 # android min sdk min:16, default 21
#  remove_alpha_ios: true
#
#  macos:
#    generate: true
#    image_path: "path/to/image.png"

  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
